### ISSUE TITLE
(Potential bug) The color sequence box can be populated with more than 4 color boxes

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#128]
Scenario:

1. The user wants to configure a color sequence for a state
2. The box for a color sequence _visually_ suggests enough space for 4 color boxes in a sequence
3. The user selects 4 color boxes to fill in the color sequence box
4. The user _is able_ to _add_ another color box to go beyond the 4 color boxes that fit in the color sequence box
5. The color box beyond the first 4 just overflows into the next line
6. The user can add as many color boxes as possible and submit

**Comment by franciscastro** [comment]
More than 4 colors are allowed but the overflow function does not behave as intended

**Comment by franciscastro** [comment]
@mmicciolo This is still buggy. I will demo this in our meeting to show the issue. The color sequence box now expands to accommodate new color squares, but when dragging the new color square into the box, it seems to make a "dummy" duplicate color box, which is visually confusing.

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @sai-educ 

This issue is ready for retesting. You now click the colors to add them to the black sequence box. The box will also expand infinitely.

There is also a trash can icon to clear the sequence.

![image](https://user-images.githubusercontent.com/23061418/139957866-4111275f-70e5-4e8a-afd7-5c570df9e8f5.png)

**Comment by mmicciolo** [comment]
Retesting Complete.
