### ISSUE TITLE
Auto Scrolling Too Fast

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#156]
In some browser windows, the auto scrolling when moving a state is too fast. 

Steps to recreate:
1. Add a state to an existing diagram.
2. Drag that state down the page.
3. On my 1366x768 resolution screen, this is way too fast and almost unusable.

**Comment by mmicciolo** [comment]
I may have found something that was amplifying this issue even more.

GameEditor.controller.js has an onRouteMatched callback so that anytime you navigate into the editor this callback is called. One of the method calls inside that is setupScrolling(). This setups the event listeners for the scrolling. This was continually getting called which was registering a bunch of handlers and would keep speeding up the scroll as more and more handlers call the same method.

I have since fixed it and now it only calls setupScrolling() the first time you navigate into the game editor instead of every time. Ie. game editor, home, gameditor, home, game editor, etc.

**Comment by mmicciolo** [comment]
Items fixed:
- Removed onmousemove when pad wasnt clicked
- When dragging a state and scrolling it now uses state position to trigger scroll
- Changing direction in scroll will cancel auto scroll

**Comment by geseiche** [comment]
@mmicciolo Testing Script ready for approval

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by franciscastro** [comment]
**Test Scenario:** Dragging a state to all 4 sides of the game editor canvas (on Mozilla Firefox browser)

**Results:**
- Functional -- I was able to drag states to all 4 sides of the game editor canvas and the scrolling speed remained at a manageable speed/pace.  There was no unmanageable speeds for scrolling experienced during testing.

---

**Other Findings**

- It works differently when run on a Chrome browser on an Android mobile phone (Pixel 5). There is no autoscrolling -- i.e., when I drag the state to the edge of the canvas, the canvas does not autoscroll. This is an edge case which I don't think needs to be addressed given that we DO NOT expect users to be developing games on an Android mobile phone.

CC: @geseiche @mmicciolo

**Comment by sai-educ** [comment]
Tested on Firefox and Safari on laptop/PC. Dragged States to all 4 sides on canvas, and the scroll speed remained at an accessible/manageable speed. 

@apoh3 One more tester needed.

**Comment by apoh3** [comment]
@mmicciolo @franciscastro @sai-educ @geseiche 

**Test passed**

Scrolling speed was good for Chrome and Edge using laptop screen and larger monitor screen.

**Comment by apoh3** [comment]
@franciscastro @mmicciolo @sai-educ @geseiche @apoh3 @IvonArroyo 
All tests complete.

For any further questions, please create a new ticket.
