### ISSUE TITLE
Error creating game and loading game

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#165]
**Description:**
I created a game named "test-issue-133". After creating the game, an error dialog displayed saying that there was an error with game creation. After I closed the error and tried loading a game, the game "test-issue-133" appeared in the options (see screenshot 1). When I loaded the "test-issue-133" game, it opened the game, but the game did not have a start state (see screenshot 2).

**Additional information:**
Screenshot 1
<img width="473" alt="Screen Shot 2021-11-22 at 10 00 08 AM" src="https://user-images.githubusercontent.com/1910413/142889663-cacdf6f4-6de2-493a-a77f-73e34cdf4a96.png">

Screenshot 2
<img width="1039" alt="Screen Shot 2021-11-22 at 10 30 50 AM" src="https://user-images.githubusercontent.com/1910413/142889680-f6a6b34a-b30b-4660-8ddf-5e6a28fb642e.png">

**Comment by franciscastro** [comment]
@mmicciolo Is the error from the create new game step related to the game name I entered? ("test-issue-133")

**Comment by mmicciolo** [comment]
Hello @franciscastro 

I checked the logs and didn't see any exceptions on the backend side of things.

When you create a new game, first it does a save with a empty game to signify create new. Then it does another save with the addition of the start state. Both of these are separate REST calls.

What I am thinking may have happened is the first save succeeded (create empty blank game) but the second save which contains the start state may have failed. Since I didn't see anything in the backend the error must have happened on the front end. Maybe a brief connection issue.

We can keep an eye on it to see if it happens again, but I don't think it has to do with the name of the game.

**Comment by mmicciolo** [comment]
Closing due to no further discoveries.
