### ISSUE TITLE
Game Manager : Error with i18n on start game instance

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#181]
![image](https://user-images.githubusercontent.com/23061418/147422577-e10cea6f-5cf4-48f3-a791-25898e609f88.png)

**Comment by mmicciolo** [comment]
Complete:
![image](https://user-images.githubusercontent.com/23061418/148248991-2905e4f4-349b-423c-965f-8f724e89f4fb.png)

**Comment by geseiche** [comment]
There was an issue with one of the calls the i18n text field. It was displaying the call
![image](https://user-images.githubusercontent.com/32133509/154689139-e805cf9f-30d2-4387-a163-11461c1a986b.png)
instead of the text.
![image](https://user-images.githubusercontent.com/32133509/154689221-eb5cec36-cf2f-4226-aa9e-42bb1efb84f0.png)

Testing
1. Log in and navigate to the game manager
2. Click start a game
3. Success if you see the message "Select a game to start from the drop down below:"

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
@mmicciolo @sai-educ @franciscastro 

**Test passed**

![image](https://user-images.githubusercontent.com/61091501/156430588-59ac27a5-f9f7-416f-aafb-8bef0bd30551.png)
![image](https://user-images.githubusercontent.com/61091501/156430632-62d98786-415c-428a-ab51-c7a19023958a.png)

**Another tester needed.**

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
