### ISSUE TITLE
Game Editor : "The given date instance isn't valid" on click history

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#186]

**Comment by mmicciolo** [comment]
Missing date on history dialog before 
![image](https://user-images.githubusercontent.com/23061418/148151721-e58b7c3e-067b-48ab-9681-9b96861ee250.png)

**Comment by mmicciolo** [comment]
Dates working as intended now:
![image](https://user-images.githubusercontent.com/23061418/148249093-d544acaf-ab6d-4640-9783-78acccd8e71f.png)

**Comment by franciscastro** [comment]
# Test Script

## Description 
Issue addressed: The date and time do not display on the Game History saves due to a `The given date instance isn't valid` error.

## Testing Scenarios
Ensure that the date and time appear for the following events in the Game History:
1. Game creation
2. State, connection, transition creation
3. State movement (start state, regular state)
4. State, connection, transition updates
5. State, connection, transition deletions
6. Manual save
7. Run and debug

## Notes
- @mmicciolo This test script is ready for review

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @geseiche @apoh3 @sai-educ 

Approved and ready for testing!

**Comment by geseiche** [comment]
Tests passed. No issues.

**Comment by franciscastro** [comment]
@mmicciolo -- this should be ready to be closed since I've also tested this when I wrote up the test script.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
