### ISSUE TITLE
Need to Refresh Manager to See Games

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#211]
When you create a game instance in the manager, the instance does not show up in the list until you refresh the screen. Found during play testing.

**Comment by mmicciolo** [comment]
@geseiche 

Going to use this ticket to make a few needed changes to the game instances UI & game server.

1. startGameInstance API should return the the started gameInstance Object (so it can be added to the list instead of needing a refresh call to get all the game instances)
2. stopGameInstance API should return the stopped gameInstance Object (so it can be removed from the list instead of needing a refresh call to get all the game instances)
3. When coming into the game instances screen (from the main selection, manager, editor, player) the UI should reset editable to false (so the Xs dont appear on the tiles)

I finished making these changes. Going to deploy shortly and write a quick test case.

**Comment by mmicciolo** [comment]
**Issue Description**
Sometimes when starting game instances in the game manager, they don't always appear in the tile container after starting. This is because after the instance is started, a call is made to refetch all of the game instances from the server. It can take a few seconds for the instance to start up so this refetch is sometimes called before the instance is fully initialized.

Now when a game instance is started, the instance information is returned from the API call and then directly added to the list of tiles so a refetch doesn't have to be done anymore.

The same goes for ending an instance, the instance that is ended is returned so that it can be removed from the tile list without having to refetch.

Another change that was done, was when you are in remove game instance mode and the X's are being displayed above the tiles if you were to go back to the editor then back to the manager the X's would still show. Now when you come back into the manager, the edit status is reset and the X's will no longer appear.

**Testing Instructions**

**Start Game Instance**

1. Login
2. Go to game manager
3. Start a game instance
4. Verify the new tile for the new instance shows up after the waiting indicator disappears
5. Repeat a few times

**End Game Instance**
1. Login
2. Go to game manager
3. End the game instances you created above one by one
4. Make sure the instance tiles disappear after the waiting indicator disappears
5. Repeat for the remaining instances you started in the testing above

**Tile X**
1. Start a game instance
2. Click the "End Game" button
3. Click the home button to go back to the main menu (manager, editor, player) 
4. Go back into the manager and make sure the X on the tile to delete the instance has disappeared

**Comment by mmicciolo** [comment]
@IvonArroyo @geseiche @sai-educ @apoh3 @franciscastro 

Fixed and ready for testing!

**Comment by geseiche** [comment]
**Tests Passed.** No issues

**Comment by apoh3** [comment]
**Tests passed.**

Tiles appeared as expected and disappeared when game ended as expected.

**Comment by mmicciolo** [comment]
Completed testing myself for 3rd tester.

Closing issue.
