### ISSUE TITLE
Behavior when clicking on a game instance (Game Manager)

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#230]
When clicking on a game instance, if there are players, we can see who the players are, which is great.

However, when there are no active players logged to that instance, there is a message saying "No data".
We would like instead to have it say "No players logged in to this game yet"

**Comment by mmicciolo** [comment]
DRAFT

Ready for testing.

This issue addresses a message when viewing the game instance info. You can view this info by going to the game manager and clicking on a game instance tile. It will show a list. If the list is empty it will now display "No one is playing this game yet" instead of "No Data."

Testing steps:
1. Navigate to game manager
2. Start a game instance
3. Click on the newly created game instance tile
4. Verify the message shows "No one is playing this game yet"
5. Navigate to the game player and join that instance
6. When you connect, hit the back button (do not disconnect)
7. Navigate to the game manager
8. Click on the game instance tile and you should see your user connected

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

This issue addresses a message when viewing the game instance info. You can view this info by going to the game manager and clicking on a game instance tile. It will show a list. If the list is empty it will now display "No one is playing this game yet" instead of "No Data."

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
This scenario tests for the correct behavior when clicking on a running game instance in the game manager.

**Steps for testing**
1. Navigate to game manager
2. Start a game instance
3. Click on the newly created game instance tile
4. Verify the message shows "No one is playing this game yet"
5. Navigate to the game player and join that instance
6. When you connect, hit the back button (do not disconnect)
7. Navigate to the game manager
8. Click on the game instance tile and you should see your user connected

**Expected behavior**
The message behavior is now different.

**Screenshots**
![image](https://user-images.githubusercontent.com/23061418/180884004-4ccf9379-df37-4b06-9881-87b75d2c439b.png)

**Comment by apoh3** [comment]
**Test passed**

![image](https://user-images.githubusercontent.com/61091501/181591169-a47d29fe-3f3d-4f90-bc00-de4ff14ff95c.png)
![image](https://user-images.githubusercontent.com/61091501/181591276-3d26f61a-414f-4db8-937f-fa39ee558a83.png)

**Comment by sai-educ** [comment]
**Test passed.** When no players join the game, the prompt says "No one is playing this game yet". When a registered user logs in, we see the login name of the player. For players that are not registered, we see a "guest" label in addition to their name, which is a nice addition. Please close this ticket. 

@mmicciolo @franciscastro @apoh3 Other observations - When you keep joining with the same pin until you exhaust the total player count, the dropdown on the Game Player screen appears to show an empty dropdown. 

![Screen Shot 2022-09-14 at 8 52 33 PM](https://user-images.githubusercontent.com/25312586/190288172-52907b48-82f7-422c-96ac-485ff17e8b66.png)

![Screen Shot 2022-09-14 at 8 59 37 PM](https://user-images.githubusercontent.com/25312586/190288758-30aac348-b93f-47b4-8221-ed4a098150d1.png)

![Screen Shot 2022-09-14 at 8 57 59 PM](https://user-images.githubusercontent.com/25312586/190288658-d064f80a-7cea-4519-84e2-8fab500be61d.png)

**Comment by mmicciolo** [comment]
Testing complete.

@sai-educ I am opening a new issue for the blank dropdown on the "choose a team and player" dialog. It is #264 

Closing issue.
