### ISSUE TITLE
Color Sequence Left/Right Buttons Clickability Indicator

### ISSUE THREAD

**Issue by apoh3** [wearable-learning-cloud-platform/wlcp-issues#239]
The left and right buttons for scrolling through color sequence input should be disabled if scrolling is not allowed in one direction. For example, if the user has scrolled all the way to the right and there are no more colors to be seen then the right button should be visibly disabled.

Related to issue #225

**Comment by mmicciolo** [comment]
Ready for testing.

I have updated the logic so that the left and right buttons are only enabled if you can scroll in that direction.

Testing Steps:

1. Create or load a game with a color sequence in a transition
2. Debug the game
3. At first left/right will be disabled since there are no sequences entered yet
4. Adding 5 sequences the left button should enable 
5. You should then be able to scroll back 1 until the left button disables and the right button enables
6. Scroll right again until right is disabled and left is enabled
7. Verify the above with more sequences

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

I have updated the logic so that the left and right buttons are only enabled if you can scroll in that direction.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
The following scenario tests that the left and right indicators enable/disable correctly.

**Steps for testing**
1. Create or load a game with a color sequence in a transition
2. Debug the game
3. At first left/right will be disabled since there are no sequences entered yet
4. Adding 5 sequences the left button should enable 
5. You should then be able to scroll back 1 until the left button disables and the right button enables
6. Scroll right again until right is disabled and left is enabled
7. Add more sequences
8. Scroll to the left and right to verify the buttons shut off when they should
9. Scroll so that you are in the middle of the sequence you are currently entering.
10. Add another color and it should jump to the end and disable the right button while leaving the left enabled
11. Verify the above with more sequences

**Comment by apoh3** [comment]
**Test passed**

Also checked if arrows disabled when sequence is cleared (worked).

Empty sequence:
![image](https://user-images.githubusercontent.com/61091501/181593214-0fb47f14-f63a-4cbf-a079-2a6ca131f9ab.png)

5 blocks in sequence:
![image](https://user-images.githubusercontent.com/61091501/181593254-7890b904-88fc-4c99-8fa2-cf795c7eca04.png)
![image](https://user-images.githubusercontent.com/61091501/181593295-f0fe4387-b4e6-4ada-b422-7467bb9d25ad.png)

In the middle of a long sequence:
![image](https://user-images.githubusercontent.com/61091501/181593397-cdb848c1-0a62-411c-92fc-13644ea02c08.png)

**Comment by sai-educ** [comment]
**Test passed.** Buttons behaving as expected. Please close this ticket. 

![Screen Shot 2022-09-14 at 9 04 57 PM](https://user-images.githubusercontent.com/25312586/190289341-a340270c-e6c0-4411-a020-c00d33b4dd14.png)
![Screen Shot 2022-09-14 at 9 04 51 PM](https://user-images.githubusercontent.com/25312586/190289342-49372f96-4474-44cb-ba62-56babd34577b.png)
![Screen Shot 2022-09-14 at 9 04 39 PM](https://user-images.githubusercontent.com/25312586/190289344-4899aef1-795b-4d18-b102-bfe81c53bf74.png)

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed.

Closing issue.
