### ISSUE TITLE
Game Debugger: More of a cell phone simulator look

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#36]
When the user debugs a Game, the debugger should launch more of a look of a simulator of a cell phone.

**Comment by mmicciolo** [comment]
![image](https://user-images.githubusercontent.com/23061418/135197771-6efdad3f-bd79-4f15-8e81-a30ae97d86c7.png)

**Comment by mmicciolo** [comment]
From #161 
Some aspects that would improve the player a lot would be:

    Background should be white or very light gray
    Username should be visible at the top
    Team should be visible at the top
    Font size should be adjusted depending on the number of characters

**Comment by mmicciolo** [comment]
Beginning to work more on concept i outlined above: 
![image](https://user-images.githubusercontent.com/23061418/147714561-174198dc-4ae4-4736-9e71-ab4a27082973.png)

**Comment by mmicciolo** [comment]
More progress on this issue.

Fully implemented it out. Commited work so far to feature/wlcp-36. Will merge soon.

![image](https://user-images.githubusercontent.com/23061418/147796722-33269694-9a55-4ef7-bf7b-42289da1d8bc.png)

**Comment by mmicciolo** [comment]
To fix:
- Saving game while debugger opens permanently shifts its position

**Comment by mmicciolo** [comment]
Merged to dev.

**Comment by mmicciolo** [comment]
This issue improves the virtual device functionality of the game editor. Before when you would run and debug games, it would open a new window with the virtual device. Sometimes this would be an issue with various popup blocks and would confused students.

Now when you run and a debug an adjustable window that is a part of the game editor appears. The size can be changed. The virtual device is now displayed inside of a "fake phone" to show that these are mobile games.

Run and Debugging a game opens this new split window. The adjuster is circled in red and adjusts the size of the window.

![image](https://user-images.githubusercontent.com/23061418/154750867-f589d482-8402-4fbd-92a1-b5ee1ce287bc.png)

The games in the debugger should work as normal as they are just the wlcp in an iframe.

Clicking the back arrows allows you to close all debuggers or individual ones. Clicking run and debug multiple times adds to this list.

![image](https://user-images.githubusercontent.com/23061418/154751032-37ed6992-702a-494f-9726-b159fc41f43f.png)

**Testing Instructions:**

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @sai-educ  @geseiche @apoh3 

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
**Test Failed?**

I loaded game test_apoh and clicked "Run and Debug". The animated three dots showed for about 30-45 seconds:
![image](https://user-images.githubusercontent.com/61091501/155239941-baf7614d-7758-4fb4-8b6d-36519798d0b9.png)

Then I received this error:
![image](https://user-images.githubusercontent.com/61091501/155239694-81c03930-267e-46a1-bfa9-1f9099aadb04.png)

After selecting close and then "See debug message" I get this popup without a message:
![image](https://user-images.githubusercontent.com/61091501/155239736-3f95cde1-4e79-4828-9782-3f6be730570b.png)

I then closed out of all popups, saved the game, and clicked "Run and Debug". I am showed the debug confirmation popup. **Is it correct for me to have to manually save before "Run and Debug"?** If so, I don't think this is clear.
![image](https://user-images.githubusercontent.com/61091501/155240287-380c95be-86f3-4ae8-8139-bdbd826b2bdb.png)

I then created a new game (test_apoh2), saved, and clicked "Run and Debug". This is my first time debugging this game. **Is it correct to be asked to "continue debugging as different player" if this is the first time debugging this game?**
![image](https://user-images.githubusercontent.com/61091501/155240287-380c95be-86f3-4ae8-8139-bdbd826b2bdb.png)

**Comment by mmicciolo** [comment]
Potential bug found. Need 1 more tester to confirm before moving back to development.

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Thanks!

**Comment by franciscastro** [comment]
**Test Scenario:** First time debugging

**Results:**
- Functional -- Debugger shows up on first "Run and Debug""

**Other Bugs found:**
- On running the debugger, the phone only displayed a blank white screen. It did not proceed to the team/player selection screen. I closed the debugger and ran it again, and on the second run, the debugger fully loaded and proceeded to the team/player selection screen (see screenshot). 

**Screenshots:**
<img width="861" alt="Screen Shot 2022-02-23 at 3 32 40 PM" src="https://user-images.githubusercontent.com/1910413/155403531-15f64022-38c5-4b84-9886-26f9b9d369a9.png">

---

**Test Scenario:** Closing the debugger with `Close All Debuggers`

**Results:**
- Functional -- Debugger closed after clicking the `Close All Debuggers` button

---

**Test Scenario:** Debugging beyond the first debug instance

**Results:**
- Functional -- When debugging beyond the first debug instance, I was presented with a dialog to select between `Start New Debug` and `Debug as Different Player` (see screenshot).

**Screenshots:**
<img width="697" alt="Screen Shot 2022-02-23 at 3 18 09 PM" src="https://user-images.githubusercontent.com/1910413/155401606-7a2f177c-8613-4f2a-a6c1-1eb1b970f630.png">

---

**Test Scenario:** Debugging with multiple instances as different players

**Results:** (see screenshots)
- Functional -- Can create multiple instances of the debugger for different players/teams (Note: created 3 debugger instances for each of T1P1, T1P2, T2P2)
- Functional -- When creating a new debug instance, the teams/players presented excludes the ones for which a debugger is already running
- Functional -- Can switch between the different debugger instances, through the "back" arrow, which displays the different debugger instances
- Functional -- When switching between debugger instances, the last state a debugger was in persists

**Screenshots:**
<img width="952" alt="Screen Shot 2022-02-23 at 3 27 31 PM" src="https://user-images.githubusercontent.com/1910413/155402861-061c60e6-1a25-4ff5-8880-ae6a141fcd96.png">
<img width="862" alt="Screen Shot 2022-02-23 at 3 22 26 PM" src="https://user-images.githubusercontent.com/1910413/155402908-9c636c16-a9c1-4373-9219-74729d6aab8e.png">
<img width="864" alt="Screen Shot 2022-02-23 at 3 22 37 PM" src="https://user-images.githubusercontent.com/1910413/155402939-40e0b5df-cd29-4736-add5-e87b95869017.png">
<img width="863" alt="Screen Shot 2022-02-23 at 3 24 53 PM" src="https://user-images.githubusercontent.com/1910413/155402964-56591fe1-26cb-4492-825b-ae81fd6fc341.png">

---

**Test Scenario:** `Close All Debuggers`

**Results:**
- Functional -- Clicking on the `Close All Debuggers` button closed all running debugger instances

--- 

**Test Scenario:** Close individual debugger instances using the `Close Current Debugger` button

**Results:**
- Failed/Bug found -- When running multiple instances of the debugger for different players/teams, closing one debugger instead closed another instead of the current debugging instance. For example, given three debugger instances with the second debugger instance active, clicking on `Close Current Debugger` closed the third debugger instance instead. This behavior is erratic in that it sometimes works correctly (i.e., closes the current active debugger instance).

---

@mmicciolo Bugs found, please review.

**Comment by mmicciolo** [comment]
Some bugs found. Moving back to development.

**Comment by mmicciolo** [comment]
Closing. Fixed white screen bug #259
